#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")
#@ load("packages.lib.yml", "package_set")

#@overlay/match by=overlay.all
---
packages:
  #@overlay/match missing_ok=True
  sets:
    - #@ package_set(packages=data.values.common_packages)
